version: "3.8"
services:
  db:
    image: postgres
    container_name: greenlight_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: 1
    volumes:
      - greenlight_pg:/var/lib/postgresql/data
volumes:
  greenlight_pg:
