version: "3.8"
services:
  app:
    build: ./
    command: ./wait-for-postgres.sh postgresdo ./main
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: 1


  postgres:
    image: postgres
    container_name: greenlight_postgres
    restart: always
    environment:
      POSTGRES_DB: greenlight
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - greenlight_pg:/var/lib/postgresql/data

volumes:
  greenlight_pg: